name: Java Tests

on:
  pull_request:
  workflow_call:

jobs:
  build-task-manager:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          repository: 'yandex-praktikum/java-kanban'
          ref: ci
          path: tests

      - name: CheckStyle
        run: |
          find ./src -type f -name "*.java" > sources.txt
          while read FILE; do
            if [ -f "$FILE" ];  then
              echo Check: $FILE
              java -jar ./tests/lib/checkstyle-10.13.0-all.jar -c ./tests/checkstyle.xml $FILE
            fi
          done < sources.txt

      - name: Build application
        run: |
          find ./src -type f -name "*.java" > sources.txt
          javac -d out -cp ./tests/lib/junit-platform-console-standalone-1.9.3.jar:./tests/lib/gson-2.10.1.jar:./src @sources.txt

      - name: Build tests
        run: |
          find ./test -type f -name "*.java" > tests.txt
          javac -d out -cp ./out:./tests/lib/junit-platform-console-standalone-1.9.3.jar:./tests/lib/gson-2.10.1.jar:./test @tests.txt

      - name: Run tests
        run: |
          java -jar ./tests/lib/junit-platform-console-standalone-1.9.3.jar --class-path ./tests/lib/gson-2.10.1.jar:./out --scan-class-path

